version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes

  back:
    build: customer-support-back
    image: yovasx2/customer-support-back
    volumes:
      - ./customer-support-back:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  
  front:
    build: customer-support-front
    image: yovasx2/customer-support-front
    volumes:
      - ./customer-support-front:/app
      - /app/node_modules # node_modules disappear between builds
    ports:
      - "4200:4200"
